### ISSUE TITLE
how timeplot deal with missing data

### ISSUE THREAD

**Issue by tingan** [jkff/timeplot#10]
Hi, 
it seems that timeplot cannot function with the present of missing data, is it a way to run timeplot by ignoring the missing data with some switch or configuration? Thanks.

**Comment by binarytemple** [comment]
How about, rather than causing the program to fail, it spits out errors to stderr ?

**Comment by jkff** [comment]
It's been a while since I did any Haskell development on my mac, and looks like my installation is completely borked. I'll catch up on the latest fashion trends in getting a working Haskell installation, and then see what I can do about validation in timeplot.

**Comment by jkff** [comment]
The program will ignore unparseable lines, but print the first 10 to stdout.

**Comment by binarytemple** [comment]
I tested it locally, it works great!
